apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsyslog
  name: rsyslog
spec:
  ports:
  - name: tcp
    port: 10514
    protocol: TCP
    targetPort: 10514
  selector:
    app: rsyslog
    rsyslog-name: ingestor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
