apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsyslog
  name: rsyslog-external
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp
    nodePort: 30514
    port: 10514
    protocol: TCP
    targetPort: 10514
  selector:
    app: rsyslog
    rsyslog-name: ingestor
  sessionAffinity: None
  type: NodePort
